spring.datasource.url=jdbc:mysql://localhost:3306/avaliacao_db
spring.datasource.username=root
spring.datasource.password=

#Ativa a criacao de tabelas automaticamente
#spring.jpa.hibernate.ddl-auto=update

#Desativa a criacao de tabelas automaticamente
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
